version: '3.9'
services:
  app:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "50505:8000"
    environment:
      AZURE_STORAGE_ACCOUNT: test-storage-account
      AZURE_STORAGE_CONTAINER: test-storage-container
      AZURE_STORAGE_RESOURCE_GROUP: test-storage-rg
      AZURE_SUBSCRIPTION_ID: test-storage-subid
      ENABLE_LANGUAGE_PICKER: 'false'
      USE_SPEECH_INPUT_BROWSER: 'false'
      USE_SPEECH_OUTPUT_AZURE: 'false'
      AZURE_SEARCH_INDEX: test-search-index
      AZURE_SEARCH_SERVICE: test-search-service
      AZURE_SPEECH_SERVICE_ID: test-id
      AZURE_SPEECH_SERVICE_LOCATION: eastus
      AZURE_OPENAI_SERVICE: test-openai-service
      AZURE_OPENAI_CHATGPT_MODEL: gpt-4.1-mini
      AZURE_OPENAI_EMB_MODEL_NAME: text-embedding-3-large
      AZURE_OPENAI_EMB_DIMENSIONS: '3072'
